### ISSUE TITLE
Permission?

### ISSUE THREAD

**Issue by KaushikDe** [physhead20/UTA-DOE-2016#2]
Tried to push CV to check things out. Got the error:

remote: Permission to physhead20/UTA-DOE-2016.git denied to KaushikDe.
fatal: unable to access 'https://github.com/physhead20/UTA-DOE-2016.git/': The requested URL returned error: 403
Pushing to https://github.com/physhead20/UTA-DOE-2016.git

**Comment by physhead20** [comment]
Added KaushikDe as collaborator...will add others once the repo is setup
